export const LUMI_TOKEN_ABI = [
  { inputs: [], name: "name", outputs: [{ name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "symbol", outputs: [{ name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "decimals", outputs: [{ name: "", type: "uint8" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalSupply", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "minter", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "address" }], name: "balanceOf", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "address" }, { name: "", type: "address" }], name: "allowance", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "_minter", type: "address" }], name: "setMinter", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], name: "mint", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], name: "transfer", outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], name: "approve", outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "from", type: "address" }, { name: "to", type: "address" }, { name: "amount", type: "uint256" }], name: "transferFrom", outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
  { anonymous: false, inputs: [{ indexed: true, name: "from", type: "address" }, { indexed: true, name: "to", type: "address" }, { indexed: false, name: "value", type: "uint256" }], name: "Transfer", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "owner", type: "address" }, { indexed: true, name: "spender", type: "address" }, { indexed: false, name: "value", type: "uint256" }], name: "Approval", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "minter", type: "address" }], name: "MinterSet", type: "event" },
] as const;

export const CROWDFUNDING_ABI = [
  // ── Getters ──────────────────────────────────────────────────────
  { inputs: [], name: "lumiToken", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "admin", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "campaignCount", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "LUMI_RATE", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "campaigns",
    outputs: [
      { name: "id", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "goal", type: "uint256" },
      { name: "raised", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "withdrawn", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ name: "", type: "uint256" }], name: "campaignApproved", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "uint256" }], name: "campaignRejected", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "uint256" }], name: "rejectionReasons", outputs: [{ name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }], name: "contributions", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }], name: "lumiClaimed", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "uint256" }], name: "returnPool", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }], name: "returnsClaimed", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  // ── Write functions ───────────────────────────────────────────────
  {
    inputs: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "goal", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    name: "createCampaign",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "approveCampaign", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }, { name: "reason", type: "string" }], name: "rejectCampaign", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "contribute", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "withdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "claimRefund", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "claimLumi", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "distributeReturns", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "claimReturn", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "getCampaignStatus", outputs: [{ name: "", type: "uint8" }], stateMutability: "view", type: "function" },
  // ── Events ────────────────────────────────────────────────────────
  { anonymous: false, inputs: [{ indexed: true, name: "id", type: "uint256" }, { indexed: true, name: "creator", type: "address" }, { indexed: false, name: "title", type: "string" }, { indexed: false, name: "goal", type: "uint256" }, { indexed: false, name: "deadline", type: "uint256" }], name: "CampaignCreated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "id", type: "uint256" }, { indexed: true, name: "admin", type: "address" }], name: "CampaignApproved", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "id", type: "uint256" }, { indexed: true, name: "admin", type: "address" }, { indexed: false, name: "reason", type: "string" }], name: "CampaignRejected", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "contributor", type: "address" }, { indexed: false, name: "amount", type: "uint256" }], name: "Contributed", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "creator", type: "address" }, { indexed: false, name: "amount", type: "uint256" }], name: "Withdrawn", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "contributor", type: "address" }, { indexed: false, name: "amount", type: "uint256" }], name: "RefundClaimed", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "contributor", type: "address" }, { indexed: false, name: "amount", type: "uint256" }], name: "LumiClaimed", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "creator", type: "address" }, { indexed: false, name: "amount", type: "uint256" }], name: "ReturnsDistributed", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "contributor", type: "address" }, { indexed: false, name: "amount", type: "uint256" }], name: "ReturnClaimed", type: "event" },
] as const;

export const GOVERNANCE_VOTING_ABI = [
  { inputs: [{ name: "crowdfundingAddress", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "crowdfunding", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "proposalCount", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "proposals",
    outputs: [
      { name: "id", type: "uint256" },
      { name: "campaignId", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "deadline", type: "uint256" },
      { name: "quorumWei", type: "uint256" },
      { name: "executed", type: "bool" },
      { name: "passed", type: "bool" },
      { name: "forVotes", type: "uint256" },
      { name: "againstVotes", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }], name: "hasVoted", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { name: "campaignId", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "votingPeriod", type: "uint256" },
      { name: "quorumWei", type: "uint256" },
    ],
    name: "createProposal",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ name: "proposalId", type: "uint256" }, { name: "support", type: "bool" }], name: "vote", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "proposalId", type: "uint256" }], name: "executeProposal", outputs: [{ name: "passed", type: "bool" }], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "getProposalResult",
    outputs: [
      { name: "votingClosed", type: "bool" },
      { name: "executable", type: "bool" },
      { name: "passed", type: "bool" },
      { name: "totalVotes", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { anonymous: false, inputs: [{ indexed: true, name: "proposalId", type: "uint256" }, { indexed: true, name: "campaignId", type: "uint256" }, { indexed: false, name: "title", type: "string" }, { indexed: false, name: "deadline", type: "uint256" }, { indexed: false, name: "quorumWei", type: "uint256" }], name: "ProposalCreated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "proposalId", type: "uint256" }, { indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "voter", type: "address" }, { indexed: false, name: "support", type: "bool" }, { indexed: false, name: "weight", type: "uint256" }], name: "VoteCast", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "proposalId", type: "uint256" }, { indexed: true, name: "campaignId", type: "uint256" }, { indexed: false, name: "passed", type: "bool" }, { indexed: false, name: "forVotes", type: "uint256" }, { indexed: false, name: "againstVotes", type: "uint256" }], name: "ProposalExecuted", type: "event" },
] as const;

export const MILESTONE_ESCROW_ABI = [
  { inputs: [{ name: "crowdfundingAddress", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "crowdfunding", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "milestoneCount", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "milestones",
    outputs: [
      { name: "id", type: "uint256" },
      { name: "campaignId", type: "uint256" },
      { name: "title", type: "string" },
      { name: "details", type: "string" },
      { name: "amountWei", type: "uint256" },
      { name: "submitted", type: "bool" },
      { name: "approved", type: "bool" },
      { name: "released", type: "bool" },
      { name: "proofURI", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ name: "", type: "uint256" }], name: "escrowBalanceByCampaign", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "uint256" }], name: "reservedBalanceByCampaign", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "depositEscrow", outputs: [], stateMutability: "payable", type: "function" },
  {
    inputs: [
      { name: "campaignId", type: "uint256" },
      { name: "title", type: "string" },
      { name: "details", type: "string" },
      { name: "amountWei", type: "uint256" },
    ],
    name: "createMilestone",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ name: "milestoneId", type: "uint256" }, { name: "proofURI", type: "string" }], name: "submitMilestoneProof", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "milestoneId", type: "uint256" }], name: "approveMilestone", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "milestoneId", type: "uint256" }], name: "releaseMilestone", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "availableEscrow", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "campaignId", type: "uint256" }], name: "getCampaignMilestones", outputs: [{ name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
  { anonymous: false, inputs: [{ indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "creator", type: "address" }, { indexed: false, name: "amount", type: "uint256" }], name: "EscrowDeposited", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "milestoneId", type: "uint256" }, { indexed: true, name: "campaignId", type: "uint256" }, { indexed: false, name: "title", type: "string" }, { indexed: false, name: "amountWei", type: "uint256" }], name: "MilestoneCreated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "milestoneId", type: "uint256" }, { indexed: true, name: "campaignId", type: "uint256" }, { indexed: false, name: "proofURI", type: "string" }], name: "MilestoneSubmitted", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "milestoneId", type: "uint256" }, { indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "admin", type: "address" }], name: "MilestoneApproved", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "milestoneId", type: "uint256" }, { indexed: true, name: "campaignId", type: "uint256" }, { indexed: true, name: "creator", type: "address" }, { indexed: false, name: "amountWei", type: "uint256" }], name: "MilestoneReleased", type: "event" },
] as const;
